# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "bastion" do |bastion|
    bastion.vm.box = "centos/7"
    bastion.vm.network "private_network", ip: "192.168.33.11"
    bastion.vm.hostname = "bastion"
    bastion.ssh.forward_agent = true
    bastion.ssh.port = 2222    
    bastion.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end
  config.vm.define "vault" do |vault|
    vault.vm.box = "centos/7"
    vault.vm.network "private_network", ip: "192.168.33.12"
    vault.vm.hostname = "vault"
    vault.ssh.forward_agent = true
    vault.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end
end
